### ISSUE TITLE
Move `solve` to `OptimalControl.jl`

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#175]
I propose to move the `solve` function to `OptimalControl.jl`.

We have to merge 

https://github.com/control-toolbox/CTDirect.jl/blob/1c0e2c607bb119a2724c4c95af583c3d793aadc5/ext/CTSolveExt.jl#L69

with

https://github.com/control-toolbox/OptimalControl.jl/blob/d139ce5cfc9c59be2e339a6045a5e1654fde2573/src/solve.jl#L67

Note that for the moment, even if in `CTDirect.jl` the `solve` function extends the one from `CommonSolve.jl` we still have the problem of qualifying for `OptimalControl .jl`. I think it would better to have only one common `solve` for an `OptimalControlModel`. In `CTDirect.jl`, we can keep the `solve` of a `DOCP`.

**Comment by PierreMartinon** [comment]
I agree that we should have the top-level `solve` in `OptimalControl` now.
The DOCP method can indeed stay in `CTDirect`. I'll see how I organise the testing at `CTDirect` level.

**Comment by ocots** [comment]
If both solve methods extends the one from commonsolve it will not interfere i think. We can keep the name solve for the resolution of a docp. Thanks to multiple dispatxh it will be ok.

**Comment by PierreMartinon** [comment]
Ok, branches for the first draft are up.
- I added a new test in `OptimalControl` for the *time_grid* option, and plan to add more tests from `CTDirect` later
- Since we currently only use the direct method, I kept the same signature as the former `solve` in `CTDirect`. We will probably adjust this when more solving methods are added.
- @ocots help needed for the CommonSolve extension, for whatever reason I don't seem to be able to get it right. Can we schedule a meeting to do it together ? (if you prefer you can do it directly on the branches and I'll catch up later).

**Comment by PierreMartinon** [comment]
Another small improvement: there is now an error message when trying to call solve without 'using NLPModelsIpopt' beforehand

**Comment by jbcaillau** [comment]
🙏🏽 @PierreMartinon 
![IMG_3349](https://github.com/user-attachments/assets/f64de45a-58d8-4efd-b57c-45dee81f5e28)
