### ISSUE TITLE
Default grid size

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#193]
@PierreMartinon @jbcaillau You don't want to pass to 200?

https://github.com/control-toolbox/CTDirect.jl/blob/a9ae483a57382d44dba0612af914d78275fd6d7a/src/CTDirect.jl#L17

ps: I put the default functions in `CTBase.jl`: https://github.com/control-toolbox/CTBase.jl/issues/221.

**Comment by PierreMartinon** [comment]
200 is fine with me !

By the way, how do we organize the default values ? I find it a bit confusing to redefine default values at multiple levels.

We could
- define everything in CTBase since every package is supposed to use it anyway
- define the 'generic' ones in CTBase and the 'specific' ones (such as the grid size above) in their related packages ?

**Comment by ocots** [comment]
Can you just take a look at the end of this comment: https://github.com/control-toolbox/CTBase.jl/pull/222#issuecomment-2272959642?

**Comment by PierreMartinon** [comment]
(I put 250 in CTDirect)

**Comment by ocots** [comment]
@PierreMartinon Do you understand why there is an error here: https://control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html?

**Comment by jbcaillau** [comment]
@ocots not an error, just convergence isssue. that is why I added state constraints to help, *e.g.*

**Comment by ocots** [comment]
Yep but its weird that with 100 it converges but not with 200. 

@PierreMartinon by the way it seems that it does not converge neither with 250 points.

**Comment by ocots** [comment]
For the doc it could be nice to have something more robust and so to change something.
