### ISSUE TITLE
Default linear solver

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#194]
@PierreMartinon @jbcaillau We choose `:ma57` or `:mumps` as default?

https://github.com/control-toolbox/CTDirect.jl/blob/a9ae483a57382d44dba0612af914d78275fd6d7a/src/CTDirect.jl#L21

ps: I put the default values in `CTBase.jl`: https://github.com/control-toolbox/CTBase.jl/issues/221.

**Comment by PierreMartinon** [comment]
For ipopt I would say mumps since the other one requires installing the HSL with a license.

Note that this choice may vary depending on the NLP solver, for instance MadNLP uses umfpack by default, not mumps... 

I suggest we use a set of default parameters for every solver we include in the algorithms, maybe prefixed by the solver name ?
- ipopt_linear_solver, ipopt_mu_strategy, etc...
- madnlp_linear_solver, madnlp_whatever, etc...
These would be used in the different methods for `solve_docp` and could be defined either in `CTBase` or `CTDirect` (see other topic about where we define the default values)

For the general `solve` we could keep a list of the most basic options that can be translated and passed to every solver, such as
- tol, max_iter, print_level*, linear_solver*
* note that these two already use differents types for ipopt and madnlp, but a straightforward conversion can be made.
Options that are not included in this list would have to be passes explicitely as kwargs.

**Comment by ocots** [comment]
A question. In `OptimalControl.jl` package we should not set default values for options that are not common to all the solvers, no ?

https://github.com/control-toolbox/OptimalControl.jl/blob/566a4c57f8f453fe0dfde05c37525a568d581491/src/solve.jl#L69

**Comment by ocots** [comment]
Another possibility is to have default values consistent with the default method:

```julia
algorithms = add(algorithms, (:direct, :adnlp, :ipopt))
```

**Comment by PierreMartinon** [comment]
Good question. I agree specific options should not appear explicitely in `solve`, and should be passed in `kwargs...`

I thought maybe we could keep some broad generic options that could fit every solver. This would be more confortable on the user side since you could have some common options regardless of the solver, but it would require a bit more work before making the actual solver calls, since the 'common' options would have to be translated. An example is the print_level for MadNLP which is not an integer oO Same with the linear solver which is not a String...
```
        if print_level == 0
            print_level = MadNLP.ERROR
        else
            print_level = MadNLP.INFO
        end
```

**Comment by ocots** [comment]
I do:

- update default in `CTBase.jl`. Do I add `madnlp_linear_solver`? What is the value?
- create in `CTDirect.jl` a file `default.jl` with its specific default values (and docstrings).
- update the `solve` of `OptimalControl.jl` to be the most simple as possible. No specific default values.

Then, we could upgrade.

**Comment by PierreMartinon** [comment]
> Another possibility is to have default values consistent with the default method:
> 
> ```julia
> algorithms = add(algorithms, (:direct, :adnlp, :ipopt))
> ```
> 
> But I prefer to have no specific default values.

Lots of possibilities :D 
Maybe we start as light as possible, and add things later ? We could go faster this way.

**Comment by ocots** [comment]
Default `madnlp_linear_solver`?

**Comment by PierreMartinon** [comment]
Conf call ?

**Comment by ocots** [comment]
> @ocots Conf call ?

Cet aprem ? 14h ?

**Comment by ocots** [comment]
We have to choose where to put:

```julia
__ipopt_print_level()
__ipopt_mu_strategy()
__ipopt_linear_solver()
__madnlp_linear_solver()
```

`CTBase.jl` or `CTDirect.jl`?

**Comment by ocots** [comment]
Mail envoyé avec lien Zoom.

**Comment by PierreMartinon** [comment]
@ocots from our discussion, `solve` will look like
```
function 
function solve(ocp::OptimalControlModel, description::Symbol...;
    init=CTBase.__ocp_init(),
    grid_size::Int=CTDirect.__grid_size(),
    time_grid=CTDirect.__time_grid(),
    kwargs...)
```
and we may later add a `CTDirect.solve_direct` intermediate function, so that the highest level `solve` would keep only *ocp, description* and *kwargs*

**Comment by ocots** [comment]
I would say. In `CTDirect.jl`:

```julia
function direct_solve(
    ocp::OptimalControlModel, 
    description::Symbol...;
    init=nothing,
    grid_size::Int=CTDirect.__grid_size(),
    time_grid=CTDirect.__time_grid(),
    kwargs...)

    method = getFullDescription(description, available_methods())

    # build discretized OCP, including initial guess
    docp, nlp = direct_transcription(ocp, description, init=init, grid_size=grid_size, time_grid=time_grid)

    # solve DOCP
    if :ipopt ∈ method
        tag = CTDirect.IpoptTag()
    elseif :madnlp ∈ method
        tag = CTDirect.MadNLPTag()
    else
        error("no known solver in method", method)
    end
    docp_solution = CTDirect.solve_docp(tag, docp, nlp; kwargs...)

    # build and return OCP solution
    return OptimalControlSolution(docp, docp_solution)

 end
```

and in `OptimalControl.jl`:

```julia
function CommonSolve.solve(
    ocp::OptimalControlModel, 
    description::Symbol...;
    kwargs...)

    method = getFullDescription(description, available_methods())

    if :direct ∈ method
        CTDirect.direct_solve(ocp, description; kwargs...)    
    end

end
```

**Comment by PierreMartinon** [comment]
Ok on the principle, although I'm not a fan of the ? : && syntax. Not readable enough to my taste :D

**Comment by PierreMartinon** [comment]
I added `direct_solve`, since we were almost done with the overhaul of the solve calls.

**Comment by ocots** [comment]
For info, I am upgrading also `CTFlows.jl` right now to incorporate the new version of `CTBase.jl`. I will be ready at the end of the day.

**Comment by PierreMartinon** [comment]
Ok ! I'll release CTDirect 0.11 now

**Comment by ocots** [comment]
> Ok ! I'll release CTDirect 0.11 now

Don't forget that we are now in the general registry.

Just need to create a new issue with a comment

```
@JuliaRegistrator register()
```

**Comment by ocots** [comment]
Oups
