### ISSUE TITLE
[Dev] Aqua tests

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#265]
@PierreMartinon I found how to use Aqua without being warn for dependencies. See https://github.com/control-toolbox/CTBase.jl/blob/main/test/test_aqua.jl.

When Aqua is used, you can add a badge. See https://github.com/control-toolbox/CTBase.jl/blob/a9744ff7cfaed4126c2bdbddce55b8adbf344010/README.md?plain=1#L38.

**Comment by amontoison** [comment]
@ocots I created a workflow to use `Aqua.jl` without adding it as a dependency:
- [https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/.github/workflows/Aqua.yml](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/.github/workflows/Aqua.yml)

I preferred this approach for Krylov.jl and the other packages in JSO because it doesn't pollute `Project.toml`.

**Comment by ocots** [comment]
@amontoison Maybe we could add something like:

```julia
PKG_SRC_PATH=`pwd`
PKG_SRC_NAME=`basename -s ".jl" $PKG_SRC_PATH`
```

to get the name of the package instead of hard-coding `Krylov`.

**Comment by amontoison** [comment]
Good idea @ocots! I will try it.
I did the script 2 years ago and was too lazy to make it generic.

**Comment by amontoison** [comment]
-> https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/873
