### ISSUE TITLE
Knot-vectors?

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#71]
@PierreMartinon @gergaud Error when solving the problem

```julia
@def ocp begin
    tf ∈ R, variable
    t ∈ [ 0, tf ], time
    x ∈ R², state
    u ∈ R, control
    tf ≥ 0
    -1 ≤ u(t) ≤ 1
    q = x₁
    v = x₂
    q(0) == 1
    v(0) == 2
    q(tf) == 0
    v(tf) == 0
    0 ≤ q(t) ≤ 5
    -2 ≤ v(t) ≤ 3
    (u^2)(t) ≤ 100
    ẋ(t) == [ v(t), u(t) ]
    tf → min
end
```

NB. The constraint `(u^2)(t) ≤ 100` is for testing purpose only

![IMG_2650](https://github.com/control-toolbox/CTDirect.jl/assets/62183989/c2704f55-5198-4967-8e00-8dbefbedb12e)
![IMG_2651](https://github.com/control-toolbox/CTDirect.jl/assets/62183989/2f24419b-796f-4320-bc38-3a78dbca6e4e)

**Comment by PierreMartinon** [comment]
If I recall correctly the knot-vector message comes sometimes from the 1D interpolation when generating the (functional) OCP solution from the discretized problem solution. I did not find the cause when looking at the time steps vector that looked fine, but the problem vanished in the CTDirect test suite when updating to Julia 1.9 or more. I'll retest this.

**Comment by PierreMartinon** [comment]
Ok, the solution generation fails here because the optimization did not converge, I'll try to find out why. Maybe we reuse something from the NLPModel solution that is not set properly when the solver fails.

On a side note, the optimization fails because the constraint tf>=0 causes Ipopt to get stuck at tf=0. Putting a strictly positive lower bound (eg 0.1) is enough to get the convergence. We may want to warn about this as it is a very common 'mistake'. I could try to detect a 0 lower bound for tf ?

**Comment by PierreMartinon** [comment]
#76
