### ISSUE TITLE
Warm start

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#75]
@PierreMartinon Write a tuto examplifying a warm start solve (*e.g.* some the same problem but with a different fixed final time, initialising with the previous solution).

NB. For current tutos, check [this](https://control-toolbox.org/docs/optimalcontrol/stable/tutorial-basic-example.html) and the [associated code](https://github.com/control-toolbox/OptimalControl.jl/blob/main/docs/src/tutorial-basic-example.md)

**Comment by PierreMartinon** [comment]
@jbcaillau, I started with a sample script trying to cover the different possibilities: default init, constant init, functional init, mix of the three, and warm start.

https://github.com/control-toolbox/CTDirect.jl/blob/init_tuto/test/test_initial_guess.jl

I'll look into the markdown examples for control-toolbox.

**Comment by PierreMartinon** [comment]
@jbcaillau Ok, you can check the Tutorial and Continuation pages at the [dev doc](https://control-toolbox.org/CTDirect.jl/dev/)

I can add a continuation example with varying final time, but it seems that time! can be used only once in the OCP definition, so I would have to redefine the whole problem for each solve. Can you confirm this ?

**Comment by PierreMartinon** [comment]
Tutorial completed

**Comment by ocots** [comment]
The redifinition like this is nice:

```julia
using CTDirect
using CTBase

function ocp_T(T)
    @def ocp begin
        t ∈ [ 0, T ], time
        x ∈ R², state
        u ∈ R, control
        q = x₁
        v = x₂
        q(0) == 0
        v(0) == 0
        q(T) == 1
        v(T) == 0
        ẋ(t) == [ v(t), u(t) ]
        ∫(u(t)^2) → min
    end
    return ocp
end
```

**Comment by ocots** [comment]
I like the fact to put the `print_level` to 0. Maybe we could print the message about convergence or make a test to print something if no convergence. Or print some errors to assert convergence.

**Comment by ocots** [comment]
It is not cool to have to declare the `Tmax` variable as `global` here even if I know it is just because we are in the global scope but not inside a function:

```julia
Tmax_list = []
obj_list = []
for Tmax_local=3.5:-0.5:1
    global Tmax = Tmax_local
    global sol = solve(ocp, print_level=0, init=OptimalControlInit(sol))
    @printf("Tmax %.2f objective %.6f iterations %d\n", Tmax, sol.objective, sol.iterations)
    push!(Tmax_list, Tmax)
    push!(obj_list, sol.objective)
end
```

**Comment by ocots** [comment]
Last thing: if the plots could be larger it would be nicer. Maybe `size=(720, 550)`.

**Comment by ocots** [comment]
Very last point: when `init=OptimalControlInit(sol)` will be changed to `init=sol`, it will rock! Nice job @PierreMartinon

**Comment by PierreMartinon** [comment]
Hi Olivier, thanks for the remarks !
- yes a 1 line output would be nice for print_level=1. I can try to work something out.
- the scope part is annoying yes, for instance when inside @testset blocks it does not count as a global variable anymore so the keywords have to be adjusted. I'll keep the example since it can be useful and the warning messages are quite clear for once, but I don't find this behaviour satisfying (treating variables inside a loop as local by default). I guess people with different programming backgrounds may find this less weird.
- agreed, do we know of a way to have the plot fill the width of the page automatically ?
- the init=sol syntax already works, I have just not used it everywhere ;-) Still working on the init branches, I have the dictionnary syntax left to do.

**Comment by jbcaillau** [comment]
@PierreMartinon @ocots we're making progess here 👍🏽
