### ISSUE TITLE
Problems with Symbolics?

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#88]
Something seems wrong with Symbolics at the moment: multiple warnings about deprecated calls, and errors on unknown method.
`ERROR: LoadError: MethodError: no method matching operation(::Symbolics.TermCombination)`
Downgrading from 5.28 to 5.27.1 does not fix the problems.
Stacktrace point to ADNLPModels, downgrading from 0.7.2 to 0.7.1 changes nothing.
Will keep watching.

**Comment by PierreMartinon** [comment]
Problem solved after some package updating. CI tests are fine now for julia 1.9 and 1.10

**Comment by PierreMartinon** [comment]
Eh, problem seems to be back on latest PR. Local tests are fine though.

**Comment by jbcaillau** [comment]
@PierreMartinon thank you for this (had not seen it). I actually just posted an [issue](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/232) on `ADNLPModels.jl`: given your comment, I am trying to update everything and re-check.

**Comment by jbcaillau** [comment]
@PierreMartinon tried to update everything but same error as yours still there.

@tmigot @amontoison any clue?

**Comment by amontoison** [comment]
I opened a PR to drop Symbolics.jl / SparseDiffTools.jl and use SparsityTracer.jl:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/230

Can you try with this branch if you have the same error?

**Comment by amontoison** [comment]
I quickly tried and It seems that `CTBase.Dynamics` is not generic enough for the sparsity analysis:
```julia
ERROR: MethodError: no method matching (::CTBase.Dynamics{…})(::Int64, ::Vector{…}, ::SparseConnectivityTracer.GradientTracer{…}, ::Vector{…})

Closest candidates are:
  (::CTBase.Dynamics{Autonomous, Fixed})(::Real, ::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}})
   @ CTBase ~/.julia/packages/CTBase/xrEbg/src/functions.jl:792
  (::CTBase.Dynamics{Autonomous, Fixed})(::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}})
   @ CTBase ~/.julia/packages/CTBase/xrEbg/src/functions.jl:788
```

**Comment by tmigot** [comment]
Hi guys! Did you manage to identify which version change introduce the bug?

**Comment by jbcaillau** [comment]
Thanks @amontoison On it, doing some checks.

> I quickly tried and It seems that `CTBase.Dynamics` is not generic enough for the sparsity analysis:
> 
> ```julia
> ERROR: MethodError: no method matching (::CTBase.Dynamics{…})(::Int64, ::Vector{…}, ::SparseConnectivityTracer.GradientTracer{…}, ::Vector{…})
> 
> Closest candidates are:
>   (::CTBase.Dynamics{Autonomous, Fixed})(::Real, ::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}})
>    @ CTBase ~/.julia/packages/CTBase/xrEbg/src/functions.jl:792
>   (::CTBase.Dynamics{Autonomous, Fixed})(::Union{Real, AbstractVector{<:Real}}, ::Union{Real, AbstractVector{<:Real}})
>    @ CTBase ~/.julia/packages/CTBase/xrEbg/src/functions.jl:788
> ```

**Comment by PierreMartinon** [comment]
Hi everyone. Not sure if this helps, but in the [CI tests](https://github.com/control-toolbox/CTDirect.jl/actions/runs/9092460877) that first failed, then passed, and now fails again, SymbolicsUtils was 1.6.0 then 1.7.0 then down to 1.6.0 again. The weird thing is that even though 1.7.0 is the latest, I only get 1.6.0 when adding the package in julia.

**Comment by jbcaillau** [comment]
Hi again @tmigot I do not know right now, but I can try to pin previous versions and check. Indeed, the typing of `CTBase.Dynamics` hasn't changed recently, so this seems to be connected with updates either of `ADNLPModels` or `Symbolic...` (or both).

@PierreMartinon any clue?

> Hi guys! Did you manage to identify which version change introduce the bug?

**Comment by PierreMartinon** [comment]
Reverting to CTDirect 0.4.6 / CTBase 0.7.2, the error is still there, and those versions passed the CI tests when they were released. I really suspect this has something to do with the symbolic operations somewhere. The 1.7.0 version of SymbolicUtils that allowed the CI to pass seems to have been unregistered, maybe they are still fixing some quirks with it. With 1.6.0 we see a lot of warnings about a deprecated istree() method, as well as the aforementioned error.

**Comment by tmigot** [comment]
It looks like this is related https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/595
I would suggest to either
- Fix SymbolicUtils to 1.5.1: ⌃ [d1185830] SymbolicUtils v1.5.1 (which is not ideal); or,
- add a comment to the SymbolicUtils issue and wait for them to fix the 1.6.

**Comment by jbcaillau** [comment]
Thanks @tmigot 
> It looks like this is related [JuliaSymbolics/SymbolicUtils.jl#595](https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/595) I would suggest to either
> 
> * Fix SymbolicUtils to 1.5.1: ⌃ [d1185830] SymbolicUtils v1.5.1 (which is not ideal); or,

Where is this dependence?

> * add a comment to the SymbolicUtils issue and wait for them to fix the 1.6.

[Done](https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/595#issuecomment-2122998926)

**Comment by amontoison** [comment]
@jbcaillau @PierreMartinon 
Off-topic: I added a breakage test for `control-toolbox/OptimalControl.jl` in ADNLPModels.jl [here](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/233).
It means that we check that we don't break anything in your ecosystem with we do a modification in ADNLPModels.jl.

**Comment by jbcaillau** [comment]
@tmigot @amontoison hi there, where exactly (= in which `toml` file) is the dependence towards SymbolicUtils.jl in ADNLPModels? 

> > It looks like this is related [JuliaSymbolics/SymbolicUtils.jl#595](https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/595) I would suggest to either
> 
> > 
> 
> > * Fix SymbolicUtils to 1.5.1: ⌃ [d1185830] SymbolicUtils v1.5.1 (which is not ideal) [...]
> 
> Where is this dependence?

**Comment by amontoison** [comment]
In ADNLPModels.jl we don't have a compat entry for Symbolics.jl because it's an optional dependency:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/ADNLPModels.jl#L185

@tmigot We should probably update ADNLPModels.jl to have a way to add compat entry for Symbolics.jl?

**Comment by tmigot** [comment]
Because, Symbolics.jl is an implicit dependency we don't have a compat for it. So, maintaining the compat for Symbolics should be on your side.

Now for SymbolicsUtils, in theory, we don't need to maintain a version compat, because it is an implicit dependency. If there is a breaking release in SymbolicsUtils, then it would later mean a breaking release in Symbolics.jl and so we usually don't see the breaking changes in SymbolicsUtils.
However, if we really need a patch now. We could add a version compatibility for SymbolicsUtils in the Project.toml and remove when we upgrade later on.

> In ADNLPModels.jl we don't have a compat entry for Symbolics.jl because it's an optional dependency: https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/ADNLPModels.jl#L185
> 
> @tmigot We should probably update ADNLPModels.jl to have a way to add compat entry for Symbolics.jl?

We have the test/Project.toml as a "guideline" for the tested version, but it is not a contrained for users of the combination ADNLPModels/Symbolics. https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/test/Project.toml @amontoison what about we temporarily add a compat entry for SymbolicUtils there?

**Comment by jbcaillau** [comment]
@tmigot @amontoison Hi guys, thank you for your input. Now I get it why I could not find a reference to `Symbolic[Utils].jl` in your `toml`. It is just `@require`d (nice mechanism, BTW).

[Require.jl] README says
> @required packages can be added to the test environment of a Julia project for integration tests, or directly to the project to document compatible versions in the [compat] section of Project.toml.

So yes, a compact somewhere would be really nice as we are stuck to `solve` anything 😬. Can be done in a `fix` branch of `ADNLPModels.jl` on which we will add a temporary dependency on our side, if you'd rather.

**Comment by amontoison** [comment]
ADNLPModels.jl doesn't install `Symbolics.jl` by default unless the user already has it. In the `control-toolbox` organization, it is a dependency of your package, so we should add more restrictive compatibility settings in your packages. We can help you with that.

Note that it's not an issue to add `SymbolicUtils.jl` as a dependency if you already have `Symbolics.jl` because it will be downloaded by `Symbolics.jl` in all cases. This will simply give us more control over the version installed, which is what we want at this point.

**Comment by jbcaillau** [comment]
Solved by @tmigot and @amontoison by this [patch](https://github.com/control-toolbox/CTDirect.jl/pull/92)

**Comment by jbcaillau** [comment]
@amontoison @tmigot although the current patch runs locally, there is still package incompatibility detected by the CI. any clue?
![IMG_3146](https://github.com/control-toolbox/CTDirect.jl/assets/62183989/0c2e36ad-839a-444d-88f7-bfbceec1a056)

**Comment by adrhill** [comment]
> I asked this modification (`<: Real`) for you 😉

Done! https://github.com/adrhill/SparseConnectivityTracer.jl/pull/92

**Comment by amontoison** [comment]
> @amontoison @tmigot although the current patch runs locally, there is still package incompatibility detected by the CI in the [patch-1](https://github.com/control-toolbox/CTDirect.jl/tree/patch-1) branch. any clue? ![IMG_3146](https://private-user-images.githubusercontent.com/62183989/332977858-0c2e36ad-839a-444d-88f7-bfbceec1a056.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjg0ODcsIm5iZiI6MTcxNjQyODE4NywicGF0aCI6Ii82MjE4Mzk4OS8zMzI5Nzc4NTgtMGMyZTM2YWQtODM5YS00NDRkLTg4ZjctYmZiY2VlYzFhMDU2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMTM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDUwNmM1YTU4M2Q0OTY2Y2Y3ZDkzOWIzYTQyYjMzYWUxOGFkZGU2ZTNiMDBkNjQ2NzYzOWFiMmUyNTliZWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R0rt81JxVy7rh3ovh9B6cBGg3K4aKqq9ayx_toQcqRI)

The compat entry on Symbolics.jl is too restrictive. It should `5` and not `5.28`.
CI failed but you merged the PR Jean-Baptiste.
I will do an hotfix.

**Comment by jbcaillau** [comment]
> > @amontoison @tmigot although the current patch runs locally, there is still package incompatibility detected by the CI in the [patch-1](https://github.com/control-toolbox/CTDirect.jl/tree/patch-1) branch.
> The compat entry on Symbolics.jl is too restrictive. It should `5` and not `5.28`.
> 
> CI failed but you merged the PR Jean-Baptiste.
> 
> I will do an hotfix.

😅 hasty me

**Comment by jbcaillau** [comment]
This [PR](https://github.com/control-toolbox/CTDirect.jl/pull/93) fixes the issue: thanks @tmigot @amontoison 

@PierreMartinon still, I suggest to leave the issue open as
- there are [ongoing changes in Symbolics.jl](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/235)
- and in [SparseConnectivityTracer.jl](https://github.com/adrhill/SparseConnectivityTracer.jl/pull/92) that might be used instead (check [above](https://github.com/control-toolbox/CTDirect.jl/issues/88#issuecomment-2121221311))

**Comment by PierreMartinon** [comment]
Back on track, thanks a lot !

**Comment by adrhill** [comment]
> [SparseConnectivityTracer.jl](https://github.com/adrhill/SparseConnectivityTracer.jl/pull/92) that might be used instead (check [above](https://github.com/control-toolbox/CTDirect.jl/issues/88#issuecomment-2121221311))

Feel free to ping me or open an issue if there is any missing functionality. Things are moving quickly and we released SparseConnectivityTracer `v0.5.0` last Friday, which [supports the majority of the NLPModels test suite](https://github.com/adrhill/SparseConnectivityTracer.jl/pull/83#issuecomment-2133028365).

**Comment by amontoison** [comment]
@PierreMartinon @jbcaillau @joseph-gergaud @ocots 
I just released ADNLPModels.jl `v0.8.0`, it should all your issues with Symbolics.jl.

I worked with Guillaume Dalle over the last few weeks and the PR https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/230 simplifies many aspects of `ADNLPModels.jl`:

- We no longer need `Symbolics.jl` and `SparseDiffTools.jl`, relying solely on `SparseConnectivityTracer.jl`.
- Jacobians and Hessians are now sparse by default. Previously, an optional dependency on `Symbolics.jl` was required.
- Faster precompilation since we no longer need to download all SciML packages.
- Fixes a major issue with `Symbolics.jl` that affected our colleagues developing `OptimalControl.jl`.
- Faster sparsity detection, with a speed-up of 100x compared to `Symbolics.jl`.
- No longer need to represent Lagrange multipliers as variables for sparsity detection, reducing memory pressure. We have the Hessian with respect to `x` and not `(x, \lambda)`.
- Fewer non-zeros in the Jacobian and Hessians, outperforming JuMP in some cases ([#83](https://github.com/adrhill/SparseConnectivityTracer.jl/pull/83#issuecomment-2133028365)). They detect more non-zeros than we do.

Next step is to improve `Colpack.jl` and try a pure Julia version (SparseMatrixColorings.jl) to perform the coloring.
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/237

The final goal is to use DifferentiationInterface.jl in ADNLPModels.jl such that we have a unified API to allocate the tape and switch the AD backends.
It also means less entretien for us.

**Comment by ocots** [comment]
Thanks Alexis for this big improvement! I pin also @frapac who should be interested.

**Comment by amontoison** [comment]
We also have benchmarks with the problems from `OptimizationProblems.jl` (https://github.com/adrhill/SparseConnectivityTracer.jl/issues/118#issue-2336266094).
We are consistently faster for the Jacobians.
As for the Hessians, it depends on the problems.

**Comment by gdalle** [comment]
Note that the speed up wrt to Symbolics was UP TO 100x, and only computed on Jacobian test cases (this was before SCT had Hessian functionality). Can't say how we would compare on Hessians. I just don't want to over promise 😉

**Comment by ocots** [comment]
> We also have benchmarks with the problems from `OptimizationProblems.jl` 

@amontoison is there a list of the problems descriptions?

**Comment by amontoison** [comment]
Not yet on.the README.md :(
But the majority of problems comes from:
- https://link.springer.com/book/10.1007/978-3-642-48320-2
- https://www.researchgate.net/publication/325314400_Sparse_Test_Problems_for_Unconstrained_Optimization
- https://dl.acm.org/doi/10.1145/355934.355936

**Comment by jbcaillau** [comment]
👍🏽 @amontoison @gdalle many thanks! having a look & try at it 🤞🏾

> @PierreMartinon @jbcaillau @joseph-gergaud @ocots I just released ADNLPModels.jl `v0.8.0`, it should fix all your issues with Symbolics.jl.
> 
> I worked with Guillaume Dalle over the last few weeks and the PR [JuliaSmoothOptimizers/ADNLPModels.jl#230](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/230) simplifies many aspects of `ADNLPModels.jl`:
> [...]
> * Fixes a major issue with `Symbolics.jl` that affected our colleagues developing `OptimalControl.jl`.
> * Faster sparsity detection, with a speed-up of 100x compared to `Symbolics.jl`.

**Comment by PierreMartinon** [comment]
Hi everyone, thanks for the update. I'll test the new 0.8 !

**Comment by gdalle** [comment]
Check out the performance benchmarks too!

**Comment by jbcaillau** [comment]
@PierreMartinon I had not noticed [this commit](https://github.com/control-toolbox/CTDirect.jl/commit/7c0d1ec1413873165adeb38e1ac488a61856ad51) that merges our colleagues changes: thanks 🙏🏽

![IMG_3211](https://github.com/control-toolbox/CTDirect.jl/assets/62183989/a6f8b98e-b70f-4b1a-9c9b-60d4cb0e58f1) 

I do not see any new release of `CTDirect`: have I missed something? Otherwise can you please do it, so that @ocots can update the dependencies in `OptimalControl.jl`?

**Comment by amontoison** [comment]
We plan to update the coloring quite soon with @gdalle.
I think it will not be breaking for ADNLPModels.jl and could include it in a release 0.8.1.
We expect a nice speed-up for Hessian coloring (~x10) but a major improvement for Jacobian coloring (~x100 -- ~x1000).

**Comment by gdalle** [comment]
>  We expect a nice speed-up for Hessian coloring (~x10) but a major improvement for Jacobian coloring (~x100 -- ~x1000).

Overselling again ;) The benchmarks are shown here https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/237

Hessian speedups will be virtually inexistent (maybe x2), Jacobian speedups will be x10 to x100 but mainly because ColPack was being used incorrectly

**Comment by amontoison** [comment]
Major speed-up for Jacobian coloring :)

**Comment by jbcaillau** [comment]
> Major speed-up for Jacobian coloring :)

@amontoison overselling you 🤭

@PierreMartinon new release...?

**Comment by amontoison** [comment]
I will release ADNLPModels.jl `v0.8.1` in 30 minutes. :rocket:

**Comment by PierreMartinon** [comment]
Nice ! I'll update CTDirect soon. We can keep the 0.8 compat entry for ADNLPModels for now to force the upgraded versions.

**Comment by jbcaillau** [comment]
@PierreMartinon looks like this issue can be closed: please do it if you're OK!

**Comment by amontoison** [comment]
The next step is to use DifferentiationInterface.jl.
We could have for a speed-up for performing the AD because I expect the tapes to be better allocated.

But the main speed-up will be related to the use of the symmetry for the coloring of the Hessian.

![Messenger_creation_8483570861670037](https://github.com/control-toolbox/CTDirect.jl/assets/35051714/8d472499-eda4-4b37-b268-766a1e9483aa)
If we have less colors, it means less directional derivates.

**Comment by PierreMartinon** [comment]
Hi everyone, 
I will close this particular issue, but the [discussion lives on] (https://github.com/control-toolbox/CTDirect.jl/discussions/111) !
